// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_beginner_escape = "CgkIssHHzqQOEAIQCQ"; // <GPGSID>
        public const string achievement_a_piece_of_cake = "CgkIssHHzqQOEAIQEA"; // <GPGSID>
        public const string achievement_boss_hunter = "CgkIssHHzqQOEAIQFg"; // <GPGSID>
        public const string achievement_im_not_afraid_of_the_boss = "CgkIssHHzqQOEAIQGA"; // <GPGSID>
        public const string achievement_now_im_the_king = "CgkIssHHzqQOEAIQDg"; // <GPGSID>
        public const string achievement_is_this_the_universe = "CgkIssHHzqQOEAIQDQ"; // <GPGSID>
        public const string achievement_its_worth_it = "CgkIssHHzqQOEAIQCA"; // <GPGSID>
        public const string achievement_too_high = "CgkIssHHzqQOEAIQDA"; // <GPGSID>
        public const string achievement_finally_bought_it_all = "CgkIssHHzqQOEAIQGg"; // <GPGSID>
        public const string leaderboard_ranking = "CgkIssHHzqQOEAIQBA"; // <GPGSID>
        public const string achievement_who_built_this_tower = "CgkIssHHzqQOEAIQCw"; // <GPGSID>
        public const string achievement_im_not_scared = "CgkIssHHzqQOEAIQEg"; // <GPGSID>
        public const string achievement_novice_hunter = "CgkIssHHzqQOEAIQDw"; // <GPGSID>
        public const string achievement_skilled_boss_hunter = "CgkIssHHzqQOEAIQFw"; // <GPGSID>
        public const string achievement_beginner = "CgkIssHHzqQOEAIQBw"; // <GPGSID>
        public const string achievement_easy_easy = "CgkIssHHzqQOEAIQCg"; // <GPGSID>
        public const string achievement_now_im_the_monster = "CgkIssHHzqQOEAIQEw"; // <GPGSID>
        public const string achievement_whos_next = "CgkIssHHzqQOEAIQEQ"; // <GPGSID>
        public const string achievement_i_almost_got_killed = "CgkIssHHzqQOEAIQFQ"; // <GPGSID>
        public const string achievement_first_character = "CgkIssHHzqQOEAIQGQ"; // <GPGSID>
        public const string achievement_growl = "CgkIssHHzqQOEAIQFA"; // <GPGSID>

}

